-- Схема таблиц category-service.
-- В микросервисной топологии у category-service своя БД (ewm_category в CI / ewm-server локально).
CREATE TABLE IF NOT EXISTS CATEGORIES
(
    ID   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    NAME VARCHAR(255) UNIQUE                     NOT NULL,
    CONSTRAINT PK_CATEGORY
    PRIMARY KEY (ID)
    );
