-- Схема таблицы user-service (users). Общая БД ewm-server.
CREATE TABLE IF NOT EXISTS USERS
(
    ID    BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    NAME  VARCHAR(255)                            NOT NULL,
    EMAIL VARCHAR(255)                            NOT NULL UNIQUE,
    CONSTRAINT PK_USER
    PRIMARY KEY (ID)
    );
