-- Схема таблицы request-service (requests). Общая БД ewm-server.
CREATE TABLE IF NOT EXISTS REQUESTS
(
    ID        BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    CREATED   TIMESTAMP WITHOUT TIME ZONE,
    EVENT     BIGINT                                  NOT NULL,
    REQUESTER BIGINT                                  NOT NULL,
    STATUS    VARCHAR(120)                            NOT NULL,
    CONSTRAINT PK_REQUEST
    PRIMARY KEY (ID)
    );
