-- Схема таблиц analyzer: сходство мероприятий и история взаимодействий.
-- CREATE TABLE IF NOT EXISTS — идемпотентно при рестарте.
CREATE TABLE IF NOT EXISTS EVENT_SIMILARITY
(
    EVENT_A BIGINT NOT NULL,
    EVENT_B BIGINT NOT NULL,
    SCORE   DOUBLE PRECISION NOT NULL,
    CONSTRAINT PK_EVENT_SIMILARITY PRIMARY KEY (EVENT_A, EVENT_B)
);

CREATE TABLE IF NOT EXISTS USER_ACTION
(
    USER_ID   BIGINT NOT NULL,
    EVENT_ID  BIGINT NOT NULL,
    WEIGHT    DOUBLE PRECISION NOT NULL,
    ACTION_AT TIMESTAMP WITH TIME ZONE,
    CONSTRAINT PK_USER_ACTION PRIMARY KEY (USER_ID, EVENT_ID)
);

CREATE INDEX IF NOT EXISTS IDX_USER_ACTION_USER ON USER_ACTION (USER_ID);
CREATE INDEX IF NOT EXISTS IDX_USER_ACTION_EVENT ON USER_ACTION (EVENT_ID);
CREATE INDEX IF NOT EXISTS IDX_EVENT_SIMILARITY_A ON EVENT_SIMILARITY (EVENT_A);
CREATE INDEX IF NOT EXISTS IDX_EVENT_SIMILARITY_B ON EVENT_SIMILARITY (EVENT_B);
